export const SYMBOLS = [
  { id: 's1', label: 'Sim', icon: 'https://www.svgrepo.com/show/434288/thumbs-up.svg', category: 'simnao' },
  { id: 's2', label: 'Não', icon: 'https://www.svgrepo.com/show/434282/thumbs-down.svg', category: 'simnao' },
  { id: 's3', label: 'Por favor', icon: 'https://www.svgrepo.com/show/434085/folded-hands.svg', category: 'simnao' },
  { id: 's4', label: 'Obrigado', icon: 'https://www.svgrepo.com/show/434235/raising-hands.svg', category: 'simnao' },
  { id: 's5', label: 'Tchau', icon: 'https://www.svgrepo.com/show/433961/waving-hand.svg', category: 'simnao' },
  { id: 's6', label: 'Parabéns', icon: 'https://www.svgrepo.com/show/434036/clapping-hands.svg', category: 'simnao' },
  { id: 's7', label: 'Gosto', icon: 'https://www.svgrepo.com/show/434113/heart.svg', category: 'simnao' },
  { id: 's8', label: 'Não gosto', icon: 'https://www.svgrepo.com/show/434018/broken-heart.svg', category: 'simnao' },
  { id: 's9', label: 'Oi', icon: 'https://www.svgrepo.com/show/398962/woman-raising-hand.svg', category: 'simnao' },
  { id: 's10', label: 'Mais', icon: 'https://www.svgrepo.com/show/286635/add-plus.svg', category: 'simnao' },
  { id: 's11', label: 'Ajuda', icon: 'https://www.svgrepo.com/show/245833/question.svg', category: 'simnao' },
  { id: 's12', label: 'Agora', icon: 'https://www.svgrepo.com/show/397693/red-exclamation-mark.svg', category: 'simnao' },

  { id: 'a1', label: 'Água', icon: 'https://www.svgrepo.com/show/297764/water-bottle-water.svg', category: 'alimentos' },
  { id: 'a2', label: 'Milho', icon: 'https://www.svgrepo.com/show/475188/corn.svg', category: 'alimentos' },
  { id: 'a3', label: 'Pão', icon: 'https://www.svgrepo.com/show/475181/bread.svg', category: 'alimentos' },
  { id: 'a4', label: 'Maçã', icon: 'https://www.svgrepo.com/show/475233/apple.svg', category: 'alimentos' },
  { id: 'a5', label: 'Leite', icon: 'https://www.svgrepo.com/show/475204/milk.svg', category: 'alimentos' },
  { id: 'a6', label: 'Café', icon: 'https://www.svgrepo.com/show/475189/cup.svg', category: 'alimentos' },
  { id: 'a7', label: 'Banana', icon: 'https://www.svgrepo.com/show/475237/banana.svg', category: 'alimentos' },
  { id: 'a8', label: 'Carne', icon: 'https://www.svgrepo.com/show/475224/steak.svg', category: 'alimentos' },
  { id: 'a9', label: 'Pizza', icon: 'https://www.svgrepo.com/show/475216/pizza.svg', category: 'alimentos' },
  { id: 'a10', label: 'Panqueca', icon: 'https://www.svgrepo.com/show/475209/pancake.svg', category: 'alimentos' },
  { id: 'a11', label: 'Biscoito', icon: 'https://www.svgrepo.com/show/475187/cookies.svg', category: 'alimentos' },
  { id: 'a12', label: 'Queijo', icon: 'https://www.svgrepo.com/show/475182/cheese.svg', category: 'alimentos' },
  { id: 'a13', label: 'Hamburguer', icon: 'https://www.svgrepo.com/show/475195/hamburger.svg', category: 'alimentos' },
  { id: 'a14', label: 'Uva', icon: 'https://www.svgrepo.com/show/475222/raspberry.svg', category: 'alimentos' },

  { id: 'f1', label: 'Feliz', icon: 'https://www.svgrepo.com/show/343904/happy.svg', category: 'sentimentos' },
  { id: 'f2', label: 'Triste', icon: 'https://www.svgrepo.com/show/343908/sad.svg', category: 'sentimentos' },
  { id: 'f3', label: 'Com sono', icon: 'https://www.svgrepo.com/show/343914/tired.svg', category: 'sentimentos' },
  { id: 'f4', label: 'Bravo', icon: 'https://www.svgrepo.com/show/343912/angry.svg', category: 'sentimentos' },
  { id: 'f5', label: 'Surpreso', icon: 'https://www.svgrepo.com/show/343910/surprised.svg', category: 'sentimentos' },
  { id: 'f6', label: 'Neutro', icon: 'https://www.svgrepo.com/show/343907/neutral.svg', category: 'sentimentos' },
  { id: 'f7', label: 'Assustado', icon: 'https://www.svgrepo.com/show/343909/scared.svg', category: 'sentimentos' },
  { id: 'f8', label: 'Animado', icon: 'https://www.svgrepo.com/show/343917/excited.svg', category: 'sentimentos' },
  { id: 'f9', label: 'Estressado', icon: 'https://www.svgrepo.com/show/343911/stressed.svg', category: 'sentimentos' },
  { id: 'f10', label: 'Doente', icon: 'https://www.svgrepo.com/show/343913/sick.svg', category: 'sentimentos' },
  { id: 'f11', label: 'Envergonhado', icon: 'https://www.svgrepo.com/show/343916/embarrassed.svg', category: 'sentimentos' },
  { id: 'f12', label: 'Incomodado', icon: 'https://www.svgrepo.com/show/343915/annoyed.svg', category: 'sentimentos' },

  { id: 'c1', label: 'Parar', icon: 'https://www.svgrepo.com/show/198740/stop.svg', category: 'acoes' },
  { id: 'c2', label: 'Escrever', icon: 'https://www.svgrepo.com/show/503663/pen-and-paper.svg', category: 'acoes' },
  { id: 'c3', label: 'Ir ao banheiro', icon: 'https://www.svgrepo.com/show/499885/bathroom.svg', category: 'acoes' },
  { id: 'c4', label: 'Dormir', icon: 'https://www.svgrepo.com/show/503673/single-bed.svg', category: 'acoes' },
  { id: 'c5', label: 'Brincar', icon: 'https://www.svgrepo.com/show/296602/play-ball-ball.svg', category: 'acoes' },
  { id: 'c6', label: 'Passear', icon: 'https://www.svgrepo.com/show/270571/pedestrian-walk.svg', category: 'acoes' },
  { id: 'c7', label: 'Ligar TV', icon: 'https://www.svgrepo.com/show/503669/tv.svg', category: 'acoes' },
  { id: 'c8', label: 'Banho', icon: 'https://www.svgrepo.com/show/503662/the-bath.svg', category: 'acoes' },
  { id: 'c9', label: 'Ler', icon: 'https://www.svgrepo.com/show/513273/book-opened.svg', category: 'acoes' },
  { id: 'c10', label: 'Esperar', icon: 'https://www.svgrepo.com/show/503644/clock.svg', category: 'acoes' },
  { id: 'c11', label: 'Vestir', icon: 'https://www.svgrepo.com/show/234666/clothes-shirt.svg', category: 'acoes' },
  { id: 'c12', label: 'Sentar', icon: 'https://www.svgrepo.com/show/311880/chair.svg', category: 'acoes' }
];

export const CATEGORIES = [
  { id: 'all', label: 'Todas', icon: 'fa-border-all' },
  { id: 'simnao', label: 'Sim / Não', icon: 'fa-check-circle' },
  { id: 'alimentos', label: 'Alimentos', icon: 'fa-utensils' },
  { id: 'sentimentos', label: 'Sentimentos', icon: 'fa-heart' },
  { id: 'acoes', label: 'Ações', icon: 'fa-hand' }
];
